import { Colors } from "./theme";

export const orangeLight: Colors = {
  surfacesAndElevation: {
    pageBackground: "#F9FAFB",
    elevation1: "#FFFFFF",
    elevation2: "#F9FAFB",
    elevation3: "#F3F4F6",
    // elevation4: "#E5E7EB",
  },
  borders: {
    borders: "#D1D5DB",
    dividers: "#E5E7EB",
    dividerBlank: "#FFFFFF",
  },
  text: {
    primary: "#181B24",
    secondary: "#4B5563",
    tertiary: "#9CA3AF",
    // placeholder: "#9CA3AF",
    // disabled: "#D1D5DB",
    color: "#FF8C21",
    gain: "#11D626",
    loss: "#FD4040",
  },
  components: {
    icon: {
      icon: "#9CA3AF",
    },
    button: {
      primary: {
        background: "#12131A",
        foreground: "#FFFFFF",
        hoverAndFocusBackground: "#181B24",
        hoverAndFocusForeground: "#FFFFFF",
        disabledBackground: "#F3F4F6",
        disabledForeground: "#D1D5DB",
      },
      secondary: {
        foreground: "#4B5563",
        hoverAndFocusBackground: "#F3F4F6",
        hoverAndFocusForeground: "#4B5563",
        disabledBorder: "#E5E7EB",
        disabledForeground: "#D1D5DB",
        border: "#D1D5DB",
        hoverAndFocusBorder: "#E5E7EB",
        background: "#F9FAFB",
      },
      // tertiary: {
      //   background: "#F3F4F6",
      //   hoverAndFocusBackground: "#F9FAFB",
      //   disabledForeground: "#D1D5DB",
      //   disabledBackground: "#F3F4F6",
      //   foreground: "#4B5563",
      //   hoverAndFocusForeground: "#4B5563",
      // },
      ghost: {
        background: "#4B5563",
        hoverAndFocusBackground: "#F3F4F6",
        hoverAndFocusForeground: "#4B5563",
        disabledBackground: "#D1D5DB",
      },
      // alert: {
      //   background: "#EB1717",
      //   foreground: "#FFF1F1",
      //   hoverAndFocusBackground: "#C60F0F",
      //   hoverAndFocusForeground: "#FFF1F1",
      //   disabledForeground: "#D1D5DB",
      //   disabledBackground: "#F3F4F6",
      // },
    },
    focusRing: {
      focusRing: "#FFC470",
    },
    badge: {
      // primaryBackground: "#FF8C21",
      // primaryForefround: "#FFFFFF",
      neutralBackground: "#F3F4F6",
      neutralForeground: "#4B5563",
      // successBackground: "#11D626",
      // successForeground: "#FFFFFF",
      alertBackground: "#EB1717",
      alertForeground: "#FFFFFF",
    },
    inputFieldCurrencyField: {
      background: "#FFFFFF",
      border: "#E5E7EB",
      // hoverBackground: "#FFFFFF",
      foreground: "#9CA3AF",
      // hoverForeground: "#9CA3AF",
      // typeAndActiveBackground: "#FFFFFF",
      typeAndActiveForeground: "#181B24",
      // borderDestructive: "#FD4040",
      // disabledBackground: "#F9FAFB",
      disabledForeground: "#D1D5DB",
      // typeAndActiveBorder: "#FF8C21",
      filledBackground: "#FFFFFF",
      filledForeground: "#181B24",
      // filledBorder: "#E5E7EB",
    },
    dropdown: {
      background: "#FFFFFF",
      foreground: "#4B5563",
      // disabledForeground: "#D1D5DB",
      hoverForeground: "#181B24",
      hoverBackground: "#F9FAFB",
    },
    chip: {
      background: "#F3F4F6",
      foreground: "#4B5563",
      // hoverAndFocusBackground: "#E5E7EB",
      // hoverAndFocusForeground: "#4B5563",
      // activeBackground: "#FF8C21",
      // activeForeground: "#FFFFFF",
      // disabledBackground: "#F3F4F6",
      // disabledForeground: "#D1D5DB",
    },
    // tab: {
    //   foreground: "#9CA3AF",
    //   hoverAndFocusBackground: "#F9FAFB",
    //   hoverAndFocusForeground: "#4B5563",
    //   activeBackground: "#F9FAFB",
    //   activeForeground: "#181B24",
    //   disabledForeground: "#D1D5DB",
    //   activeHoverAndFocusBackground: "#F9FAFB",
    //   activeHoverAndFocusForeground: "#181B24",
    // },
    toggle: {
      activeDefaultBackground: "#FF8C21",
      activeDefaultForeground: "#FFFFFF",
      // activeDisabledBackground: "#FF9F37",
      // activeDisabledForeground: "#F06706",
      // inactiveDisabledBackground: "#E5E7EB",
      // inactiveDisabledForeground: "#D1D5DB",
      inactiveDefaultBackground: "#E5E7EB",
      // inactiveDefaultForeground: "#FFFFFF",
      // inactiveHoverAndFocusBackground: "#E5E7EB",
      // inactiveHoverAndFocusForeground: "#F9FAFB",
      // activeHoverAndFocusBackground: "#F06706",
      // activeHoverAndFocusForeground: "#FFFFFF",
    },
    // segmentationControl: {
    //   baseInactiveHoverAndFocusForeground: "#4B5563",
    //   baseActiveBackground: "#F9FAFB",
    //   baseActiveForeground: "#181B24",
    //   baseDisabledForeground: "#9CA3AF",
    //   background: "#F9FAFB",
    //   baseInactiveForeground: "#9CA3AF",
    //   border: "#E5E7EB",
    // },
    tooltip: {
      background: "#181B24",
      foreground: "#FFFFFF",
    },
    // radioButton: {
    //   selectedDefaultBackground: "#FF8C21",
    //   selectedDefaultForeground: "#FFFFFF",
    //   selectedHoverAndFocusBackground: "#F06706",
    //   selectedHoverAndFocusForeground: "#FFFFFF",
    //   selectedDisabledBackground: "#E5E7EB",
    //   selectedDisabledForeground: "#D1D5DB",
    //   unselectedStroke: "#D1D5DB",
    //   unselectedHoverAndFocusBackground: "#FFF8ED",
    //   unselectedHoverAndFocusForeground: "#C74D07",
    //   unselectedDisabledBackground: "#F3F4F6",
    //   unselectedDisabledStroke: "#E5E7EB",
    //   unselectedHoverAndFocusStroke: "#FF8C21",
    // },
    // checkbox: {
    //   unselectedStroke: "#D1D5DB",
    //   unselectedHoverAndFocusStroke: "#FF8C21",
    //   unselectedHoverAndFocusBackground: "#FFF8ED",
    //   unselectedHoverAndFocusForeground: "#C74D07",
    //   unselectedDisabledStroke: "#E5E7EB",
    //   unselectedDisabledBackground: "#F3F4F6",
    //   selectedDefaultBackground: "#FF8C21",
    //   selectedDefaultForeground: "#FFFFFF",
    //   selectedHoverAndFocusBackground: "#F06706",
    //   selectedHoverAndFocusForeground: "#FFFFFF",
    //   selectedDisabledBackground: "#E5E7EB",
    //   selectedDisabledForeground: "#D1D5DB",
    // },
    // selector: {
    //   border: "#E5E7EB",
    //   hoverBackground: "#FFFFFF",
    //   activeBackground: "#FFFFFF",
    // },
    textButton: {
      // secondary: {
      //   default: "#181B24",
      //   hoverAndFocus: "#181B24",
      //   disabled: "#D1D5DB",
      // },
      primary: {
        default: "#FF8C21",
        // hoverAndFocus: "#F06706",
        // disabled: "#D1D5DB",
      },
      tertiary: {
        default: "#9CA3AF",
        // hoverAndFocus: "#6B7280",
        // disabled: "#D1D5DB",
      },
    },
    graph: {
      main: "#FF8C21",
      // secondary: "#FF9F37",
    },
  },
};

export const orangeDark: Colors = {
  surfacesAndElevation: {
    pageBackground: "#000103",
    elevation1: "#12131A",
    elevation2: "#181B24",
    elevation3: "#273345",
    // elevation4: "#374151",
  },
  borders: {
    borders: "#273345",
    dividers: "#374151",
    dividerBlank: "#12131A",
  },
  text: {
    primary: "#FFFFFF",
    secondary: "#D1D5DB",
    tertiary: "#9CA3AF",
    // placeholder: "#9CA3AF",
    // disabled: "#6B7280",
    color: "#FF8C21",
    gain: "#4FEF5F",
    loss: "#FD4040",
  },
  components: {
    icon: {
      icon: "#9CA3AF",
    },
    button: {
      primary: {
        background: "#F3F4F6",
        foreground: "#12131A",
        hoverAndFocusBackground: "#FFFFFF",
        hoverAndFocusForeground: "#12131A",
        disabledBackground: "#273345",
        disabledForeground: "#6B7280",
      },
      secondary: {
        foreground: "#D1D5DB",
        hoverAndFocusBackground: "#273345",
        hoverAndFocusForeground: "#D1D5DB",
        disabledBorder: "#273345",
        disabledForeground: "#4B5563",
        border: "#273345",
        hoverAndFocusBorder: "#273345",
        background: "#181B24",
      },
      // tertiary: {
      //   background: "#374151",
      //   hoverAndFocusBackground: "#4B5563",
      //   disabledForeground: "#6B7280",
      //   disabledBackground: "#273345",
      //   foreground: "#D1D5DB",
      //   hoverAndFocusForeground: "#D1D5DB",
      // },
      ghost: {
        background: "#D1D5DB",
        hoverAndFocusBackground: "#273345",
        hoverAndFocusForeground: "#D1D5DB",
        disabledBackground: "#6B7280",
      },
      // alert: {
      //   background: "#A31111",
      //   foreground: "#FFE0E0",
      //   hoverAndFocusBackground: "#C60F0F",
      //   hoverAndFocusForeground: "#FFE0E0",
      //   disabledForeground: "#6B7280",
      //   disabledBackground: "#273345",
      // },
    },
    focusRing: {
      focusRing: "#FFC470",
    },
    badge: {
      // primaryBackground: "#FF8C21",
      // primaryForefround: "#FFFFFF",
      neutralBackground: "#273345",
      neutralForeground: "#F3F4F6",
      // successBackground: "#013208",
      // successForeground: "#4FEF5F",
      alertBackground: "#4A0505",
      alertForeground: "#FD4040",
    },
    inputFieldCurrencyField: {
      background: "#181B24",
      border: "#374151",
      // hoverBackground: "#273345",
      foreground: "#9CA3AF",
      // hoverForeground: "#9CA3AF",
      // typeAndActiveBackground: "#181B24",
      typeAndActiveForeground: "#FFFFFF",
      // borderDestructive: "#FD4040",
      // disabledBackground: "#181B24",
      disabledForeground: "#6B7280",
      // typeAndActiveBorder: "#FF8C21",
      filledBackground: "#181B24",
      filledForeground: "#FFFFFF",
      // filledBorder: "#374151",
    },
    dropdown: {
      background: "#181B24",
      foreground: "#D1D5DB",
      // disabledForeground: "#6B7280",
      hoverForeground: "#FFFFFF",
      hoverBackground: "#181B24",
    },
    chip: {
      background: "#273345",
      foreground: "#D1D5DB",
      // hoverAndFocusBackground: "#374151",
      // hoverAndFocusForeground: "#D1D5DB",
      // activeBackground: "#FF8C21",
      // activeForeground: "#FFFFFF",
      // disabledBackground: "#273345",
      // disabledForeground: "#6B7280",
    },
    // tab: {
    //   foreground: "#9CA3AF",
    //   hoverAndFocusBackground: "#181B24",
    //   hoverAndFocusForeground: "#D1D5DB",
    //   activeBackground: "#273345",
    //   activeForeground: "#FFFFFF",
    //   disabledForeground: "#6B7280",
    //   activeHoverAndFocusBackground: "#273345",
    //   activeHoverAndFocusForeground: "#FFFFFF",
    // },
    toggle: {
      activeDefaultBackground: "#FF8C21",
      activeDefaultForeground: "#FFFFFF",
      // activeDisabledBackground: "#FF9F37",
      // activeDisabledForeground: "#F06706",
      // inactiveDisabledBackground: "#374151",
      // inactiveDisabledForeground: "#6B7280",
      inactiveDefaultBackground: "#374151",
      // inactiveDefaultForeground: "#F3F4F6",
      // inactiveHoverAndFocusBackground: "#4B5563",
      // inactiveHoverAndFocusForeground: "#F3F4F6",
      // activeHoverAndFocusBackground: "#C74D07",
      // activeHoverAndFocusForeground: "#FFFFFF",
    },
    // segmentationControl: {
    //   baseInactiveHoverAndFocusForeground: "#D1D5DB",
    //   baseActiveBackground: "#273345",
    //   baseActiveForeground: "#FFFFFF",
    //   baseDisabledForeground: "#9CA3AF",
    //   background: "#181B24",
    //   baseInactiveForeground: "#9CA3AF",
    //   border: "#374151",
    // },
    tooltip: {
      background: "#273345",
      foreground: "#FFFFFF",
    },
    // radioButton: {
    //   selectedDefaultBackground: "#FF8C21",
    //   selectedDefaultForeground: "#FFFFFF",
    //   selectedHoverAndFocusBackground: "#9E3C0E",
    //   selectedHoverAndFocusForeground: "#FFFFFF",
    //   selectedDisabledBackground: "#374151",
    //   selectedDisabledForeground: "#6B7280",
    //   unselectedStroke: "#273345",
    //   unselectedHoverAndFocusBackground: "#C74D07",
    //   unselectedHoverAndFocusForeground: "#FF9F37",
    //   unselectedDisabledBackground: "#4B5563",
    //   unselectedDisabledStroke: "#273345",
    //   unselectedHoverAndFocusStroke: "#FF8C21",
    // },
    // checkbox: {
    //   unselectedStroke: "#273345",
    //   unselectedHoverAndFocusStroke: "#FF8C21",
    //   unselectedHoverAndFocusBackground: "#C74D07",
    //   unselectedHoverAndFocusForeground: "#FFDDA8",
    //   unselectedDisabledStroke: "#273345",
    //   unselectedDisabledBackground: "#4B5563",
    //   selectedDefaultBackground: "#FF8C21",
    //   selectedDefaultForeground: "#FFFFFF",
    //   selectedHoverAndFocusBackground: "#FF8C21",
    //   selectedHoverAndFocusForeground: "#FFFFFF",
    //   selectedDisabledBackground: "#374151",
    //   selectedDisabledForeground: "#6B7280",
    // },
    // selector: {
    //   border: "#374151",
    //   hoverBackground: "#181B24",
    //   activeBackground: "#181B24",
    // },
    textButton: {
      // secondary: {
      //   default: "#FFFFFF",
      //   hoverAndFocus: "#F3F4F6",
      //   disabled: "#6B7280",
      // },
      primary: {
        default: "#FF8C21",
        // hoverAndFocus: "#FF9F37",
        // disabled: "#6B7280",
      },
      tertiary: {
        default: "#9CA3AF",
        // hoverAndFocus: "#9CA3AF",
        // disabled: "#6B7280",
      },
    },
    graph: {
      main: "#FF8C21",
      // secondary: "#F06706",
    },
  },
};
